#define EXIT_ALLOC_FAILURE 2
#define EXIT_POP_FAILURE 3
#define EXIT_CLI_ILLEGAL 4

#define ACTION_NOTHING 0
#define ACTION_IGNORE_CONFIG_FILE 1
#define ACTION_DONT_ASK_CONFIG_OPTIONS 2
#define ACTION_SAVE_TO_FILE 4
#define ACTION_BE_VERBOSE 8
#define ACTION_GO 16
#define ACTION_HELP 17