#ifndef _LOGS_CONFIGURATION_H_
    /// @brief Include guard.
    #define _LOGS_CONFIGURATION_H_

    /// @brief The length of the string "logs/dd-MM-yyyy_hh,mm,ss.log", that is the pattern of the filename of every log file generated by this program.
    #define fileNameBufferSize 29
    
    /// @brief The configuration for the logger.
    typedef struct LogsConfiguration {
        /// @brief The filename path to the log file used in a session. It can be a valid path or an empty string if the program failed when generating the file.
        char fileName[fileNameBufferSize];
        /// @brief Flag for the logger to determine if it has to use the console or the log file.
        bool useConsole;
    } LogsConfiguration;
#endif