// Copyright (C) 2025  Giulio Salvi, Jacopo Paradisi
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

/**
 * \file
 * \brief Definition of logger configuration structure.
**/

#ifndef _LOGS_CONFIGURATION_H_
    /// @brief Include guard.
    #define _LOGS_CONFIGURATION_H_

    /// @brief The length of the string "logs/dd-MM-yyyy_hh,mm,ss.log", that is the pattern of the filename of every log file generated by this program.
    #define fileNameBufferSize 29
    
    /// @brief The configuration for the logger.
    typedef struct LogsConfiguration {
        /// @brief The filename path to the log file used in a session. It can be a valid path or an empty string if the program failed when generating the file.
        char fileName[fileNameBufferSize];
        /// @brief Flag for the logger to determine if it has to use the console or the log file.
        bool useConsole;
    } LogsConfiguration;
#endif