#include "../h/includes.h"
#include "../h/ansi.h"

typedef enum CardSeeds {
    Clubs,
    Spades,
    Diamonds,
    Hearts
} CardSeeds;

typedef enum CardNumber {
    One = 1,
    Two = 2,
    Three = 3, 
    Four = 4,
    Five = 5,
    Six = 6,
    Seven = 7,
    Jack = 8,
    Queen = 9,
    King = 10
} CardNumber;

typedef struct Card {
    CardSeeds seed;
    CardNumber number;
} Card;

typedef struct Player {
    int id;
    int lifePoints;
    Card* facedUpCard;
    Card* facedDownCard;
} Player;

typedef struct Game {
    int playersCounter;
    int lifePointsOnTheField;
    Player** players;
} Game;

/// Generates a random number between min and max included.
int randomInt(int min, int max);

/// @brief Asks the number of players to the user.
/// @return The number of players.
int askPlayerNumber();
/// Generates a card with card's seed and number set to -1.
Card* buildCard();
/// Generates a deck of 40 cards, generated by buildCard().
Card** buildDeck();
/// Generates a player with player's id to -1. Player's cards are built by buildCard. lifePoints property is unset.
Player* buildPlayer();
/// Generates a game with the given number of players. Players are built by buildPlayer. lifePointsOnTheField is unset.
Game buildGame(int playersCounter);

/// Generates a deck with cards ordered randomly.
Card** prepareCardDeck();
/// Generates a player structure with the given player id.
Player* preparePlayer(int id, Card** deck);
/// Generates a game structure with the given players number.
Game prepareGame(int playersCounter, Card** deck);
/// Shuffles the deck using Fisher - Yates algorithm.
void shuffleDeck(Card** deck);

/// Checks if a card is present in a deck.
bool deckHasCard(Card** deck, Card card);
/// Checks if two cards are equal (it does not consider if the cards are faced down).
bool cardAreEqual(Card card1, Card card2);
/// Checks if the cards of a given player have been already given to other players.
bool cardsWereGiven(Player** players, int playersCounter, Player player);

/// Prints card's seed and number.
void printCard(Card card, bool newLine);
/// Prints player's info.
void printPlayer(Player player, bool newLine);

int main() {
    //
    // return 0;
    srand(time(NULL));
    initialClearScreen();
    
    Card** deck = prepareCardDeck();
    int playersCounter = askPlayerNumber();

    Game game = prepareGame(playersCounter, deck);
    // for(int i = 0; i < game.playersCounter; i++)
    //     printPlayer(*game.players[i], true);

    return 0;
}

int randomInt(int min, int max) {
    return rand()%(max - min + 1) + min;
}

int askPlayerNumber() {
    bool first = true;
    int playersCounter = 0;

    do {
        if(!first) {
            playersCounter = 0;
            clearScreen();
            
            printfgr("#b##%d#The players number must be between 2 and 20.\n#r#", (int)FgBrightRed);
        } else
            first = false;

        printgr("#b#Please, insert the players number: #r#");
        inputf("%d", &playersCounter);
    } while(playersCounter < 2 || playersCounter > 20);

    return playersCounter;
}

Card* buildCard() {
    Card* card = malloc(sizeof(Card));

    card->seed = -1;
    card->number = -1;

    return card;
}

Card** buildDeck() {
    Card** deck = malloc(sizeof(Card*)*40);

    for(int i = 0; i < 40; i++)
        deck[i] = buildCard();

    return deck;
}

Player* buildPlayer() {
    Player* player = malloc(sizeof(Player));

    player->id = -1;
    player->facedUpCard = buildCard();
    player->facedDownCard = buildCard();

    return player;
}

Game buildGame(int playersCounter) {
    Game game;

    game.playersCounter = playersCounter;
    game.players = malloc(sizeof(Player*)*game.playersCounter);

    for(int i = 0; i < game.playersCounter; i++)
        game.players[i] = buildPlayer();

    return game;
}

Card** prepareCardDeck() {
    Card** deck = buildDeck();

    for(int i = 0; i < 40; i++) {
        Card* card = buildCard();

        do {
            card->seed = randomInt(0, 3); 
            card->number = randomInt(1, 10);
        } while(deckHasCard(deck, *card));

        deck[i] = card;
    }

    return deck;
}

Game prepareGame(int playersCounter, Card** deck) {
    Game game = buildGame(playersCounter);
    game.lifePointsOnTheField = 0;

    for(int i = 0; i < game.playersCounter; i++) {
        Player* player = malloc(sizeof(Player));
        
        do
            player = preparePlayer(i + 1, deck);
        while(cardsWereGiven(game.players, game.playersCounter, *player) || cardAreEqual(*player->facedUpCard, *player->facedDownCard));

        game.players[i] = player;
    }

    return game;
}

Player* preparePlayer(int id, Card** deck) {
    Player* player = buildPlayer();

    player->id = id;
    player->lifePoints = 2;
    player->facedUpCard = deck[randomInt(0, 39)];
    player->facedDownCard = deck[randomInt(0, 39)];

    return player;
}

void shuffleDeck(Card** deck) {
    for(int i = 39; i > 0; i--) {
        int j = randomInt(0, i);

        Card* tmp = deck[i];
        deck[i] = deck[j];
        deck[j] = tmp;
    }
}

bool deckHasCard(Card** deck, Card card) {
    for(int i = 0; i < 40; i++)
        if(cardAreEqual(*deck[i], card))
            return true;
    
    return false;
}

bool cardAreEqual(Card card1, Card card2) {
    return card1.number == card2.number && card1.seed == card2.seed;
}

bool cardsWereGiven(Player** players, int playersCounter, Player player) {
    for(int i = 0; i < playersCounter; i++)
        if(cardAreEqual(*player.facedDownCard, *players[i]->facedDownCard) || cardAreEqual(*player.facedUpCard, *players[i]->facedUpCard))
            return true;

    return false;
}

void printCard(Card card, bool newLine) {
    switch(card.seed) {
        case Clubs:
            printgr("Clubs");
            break;
        case Spades:
            printgr("Spades");
            break;
        case Diamonds:
            printgr("Diamonds");
            break;
        case Hearts:
            printgr("Hearts");
            break;
    }

    printgr(" ");

    switch(card.number) {
        case One:
            printgr("One");
            break;
        case Two:
            printgr("Two");
            break;
        case Three:
            printgr("Three");
            break;
        case Four:
            printgr("Four");
            break;
        case Five:
            printgr("Five");
            break;
        case Six:
            printgr("Six");
            break;
        case Seven:
            printgr("Seven");
            break;
        case Jack:
            printgr("Jack");
            break;
        case Queen:
            printgr("Queen");
            break;
        case King:
            printgr("King");
            break;
    }

    if(newLine)
        printgr("\n");
}

void printPlayer(Player player, bool newLine) {
    printfgr("Player #b#%d#r# with #b#%d LPs#r# has cards #b#", player.id, player.lifePoints);

    printCard(*player.facedUpCard, false);
    printgr("#r# faced up and #b#");
    printCard(*player.facedDownCard, false);
    printgr("#r# faced down.");

    if(newLine)
        printgr("\n");
}